---
name: "Playback Reporting"
guid: "5c534381-91a3-43cb-907a-35aa02eb9d2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-playbackreporting.png"
version: 13
targetAbi: "10.8.1.0"
framework: net6.0
owner: "jellyfin"
overview: "Collect and show user play statistics"
description: "Collect and show user play statistics"
category: "General"
artifacts:
  - "Jellyfin.Plugin.PlaybackReporting.dll"
changelog: |2-
  ### Bug Fixes ###
  - Added support for decimal timezones (#64) @theKAKAN
  - Keep all avatars the same dimension (#62) @sambartik

  ### CI & build changes ###
  - fix: meta ci workflows (#60) @h1dden-da3m0n
